# Generated by Django 4.2.1 on 2023-06-07 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('flag', models.CharField(choices=[('Added', 'Added'), ('Not-Added', 'Not-Added')], default='Not-Added', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('measure_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveTemplate',
            fields=[
                ('objective_id', models.AutoField(primary_key=True, serialize=False)),
                ('objective_name', models.CharField(max_length=200)),
                ('objective_subcategory', models.CharField(blank=True, max_length=200)),
                ('target', models.IntegerField(blank=True, default=0)),
                ('weightage', models.IntegerField(blank=True, default=0)),
                ('lower_percentage_for_weighted_score_calculation', models.IntegerField(blank=True, default=70)),
                ('upper_percentage_for_weighted_score_calculation', models.IntegerField(blank=True, default=120)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapp.measure')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='WeightageScoreQuarterly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('weighatage_sum', models.IntegerField()),
                ('first_quarter_value', models.IntegerField()),
                ('second_quarter_value', models.IntegerField()),
                ('third_quarter_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('objective', models.ManyToManyField(blank=True, to='employeeapp.objectivetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_name', models.CharField(default=None, max_length=1000)),
                ('company_name', models.CharField(default=None, max_length=1000)),
                ('project', models.CharField(default=None, max_length=1000)),
                ('technology', models.CharField(default=None, max_length=1000)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close'), ('Active', 'Active'), ('On-HOld', 'On-HOld')], default=None, max_length=1000)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='objectivetemplate',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapp.role'),
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('objective_id', models.AutoField(primary_key=True, serialize=False)),
                ('objective_name', models.CharField(max_length=200)),
                ('objective_subcategory', models.CharField(blank=True, max_length=200)),
                ('target', models.IntegerField(blank=True, default=0)),
                ('weightage', models.IntegerField(blank=True, default=0)),
                ('actual', models.IntegerField(blank=True, default=0)),
                ('final', models.IntegerField(blank=True, default=0)),
                ('achieved', models.IntegerField(blank=True, default=0)),
                ('mbo_achievement', models.IntegerField(blank=True, default=None)),
                ('weighted_score', models.IntegerField(blank=True, default=None)),
                ('lower_percentage_for_weighted_score_calculation', models.IntegerField(blank=True, default=70)),
                ('upper_percentage_for_weighted_score_calculation', models.IntegerField(blank=True, default=120)),
                ('year', models.IntegerField(default=0)),
                ('quarter', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Sent-To-Manager', 'Sent-To-Manager'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Updated-By-Manager', 'Updated-By-Manager'), ('Sent-To-Supervisor', 'Sent-To-Supervisor'), ('Sent-To-Supervisor-After-Rejecting', 'Sent-To-Supervisor-After-Rejecting'), ('Sent-Back-To-Manager', 'Sent-Back-To-Manager'), ('Updated-By-Supervisor', 'Updated-By-Supervisor'), ('Approved', 'Approved')], default='Created', max_length=100)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapp.manager')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapp.measure')),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapp.supervisor'),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('flag', models.CharField(choices=[('Added', 'Added'), ('Not-Added', 'Not-Added')], default='Not-Added', max_length=100)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapp.manager')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
