# Generated by Django 4.1.3 on 2023-05-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectivetemplate',
            name='manager',
        ),
    ]
