# Generated by Django 4.2.1 on 2023-06-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objective',
            old_name='target',
            new_name='target1',
        ),
        migrations.RenameField(
            model_name='objectivetemplate',
            old_name='target',
            new_name='target1',
        ),
        migrations.AddField(
            model_name='objective',
            name='medium_percentage_for_weighted_score_calculation',
            field=models.IntegerField(blank=True, default=80),
        ),
        migrations.AddField(
            model_name='objective',
            name='target2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='objective',
            name='target3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='objectivetemplate',
            name='medium_percentage_for_weighted_score_calculation',
            field=models.IntegerField(blank=True, default=90),
        ),
        migrations.AddField(
            model_name='objectivetemplate',
            name='target2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='objectivetemplate',
            name='target3',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
